concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Main Runner"
  url = "http://git.maindomain.com/"
  token = "ZBY9"
  executor = "shell"
  environment = ["DeployScriptPath=/home/runner/scripts","RunnerPath=/home/gitlab-runner/runner","Proj1RunnerPath=/home/gitlab-runner/Proj1-runner","proj2=runner@x.x.x.11","proj3=runner@x.x.x.40","proj4=runner@x.x.x.120","proj5=runner@x.x.x.x.42","proj5=runner@x.x.x.122","proj5SWARM=runner@x.x.x.50","PRODUCTION=runner@x.x.x.22","PRODUCTIONSWARM=runner@x.x.x.x.80","AdminPanel=runner@x.x.x.x.35","ComposePath=/home/runner/compose","USERCI=test","ACCESSCI=6z-5gRP_W","REGISTRYCI=gitregistry.mydomain.ir"]
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "Docker Runner"
  url = "http://192.168.50.12/"
  token = "dtYxx"
  executor = "docker"
  environment = ["SIT=runner@x.x.x.11"]
  clone_url = "http://x.x.x.12"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "openjdk:8u181-jdk-alpine3.8"
    privileged = true
    extra_hosts = ["SIT:x.x.x.11"]
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/gitlab-runner/builds/docker-runner/swagger-ui/:/swagger-ui/", "/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
