# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:

# ------------------------- prometheus ----------------------------
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']
# -------------------------- cadvisor -----------------------------
  - job_name: 'cadvisor'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080
# -------------------------- Node Exporter -----------------------
  - job_name: 'node-exporter'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

# ------------------- 50.66 -------------------------------------
  - job_name: 'node-exporter:50.66'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.66:9100']
        labels:
           job: 'node'
           instance: '50.66'

# ------------------- Release 50.* -------------------------------------
  - job_name: 'node-exporter:50.50'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.50:9100']
        labels:
           job: 'node'
           instance: '50.50'

  - job_name: 'node-exporter:50.51'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.51:9100']
        labels:
           job: 'node'
           instance: '50.51'

# ----------------- 50.66 --------------------------------------
  - job_name: 'CAdvisor:50.66'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.66:8080']

#--------------------- SIT ------------------------------------
  - job_name: 'node-exporter:50.11'
    scrape_interval: 5s
    static_configs:
       - targets: ['192.168.50.11:9100']
         labels:
           job: 'node'
           instance: '50.11'
#--------------------- Release-cadvisor ------------------------------------
  - job_name: 'release-cadvisor:50.50'
    scrape_interval: 5s
    static_configs:
       - targets: ['192.168.50.50:8080']
#--------------------------------------------------------------


#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    dns_sd_configs:
#    - names:
#      - 'tasks.pushgateway'
#      type: 'A'
#      port: 9091

#     static_configs:
#          - targets: ['node-exporter:9100']
