---
global:
  resolve_timeout: 1m
#  slack_api_url: "https://hooks.slack.com/services/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"

route:
  receiver: 'slack-notifications'

receivers:
  - name: slack-notifications
    slack_configs:
    - send_resolved: true
      channel: '#prometheus-alertmanager'
      api_url: 'https://hooks.slack.com/services/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'
      icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
      text: |-
            {{ range .Alerts -}} *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
            *Description:* {{ .Annotations.description }}
            *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
            {{ end }}
      title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
            {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
              {{" "}}(
              {{- with .CommonLabels.Remove .GroupLabels.Names }}
                {{- range $index, $label := .SortedPairs -}}
                  {{ if $index }}, {{ end }}
                  {{- $label.Name }}="{{ $label.Value -}}"
                {{- end }}
              {{- end -}}
              )
            {{- end }}

